import Testing
@testable import BanyanCore

@Test func displayLabelUsesProjectBranchAndExplicitTitle() {
    let label = SessionDisplayLabel.make(
        project: "banyan",
        branch: "main",
        title: "what's the label",
        id: "session",
        command: ""
    )

    #expect(label == "banyan · main · \"what's the label\"")
}

@Test func displayLabelFallsBackFromGenericTitleToShell() {
    let label = SessionDisplayLabel.make(
        project: "banyan",
        branch: "main",
        title: "Shell",
        id: "Shell-2",
        command: ""
    )

    #expect(label == "banyan · main · \"shell\"")
}

@Test func displayLabelIgnoresHostTitleAndUsesAgentPrompt() {
    let label = SessionDisplayLabel.make(
        project: "banyan",
        branch: "main",
        title: "banyudu@Yudus-MacBook-Pro.local",
        id: "session",
        command: "codex implement the sidebar label"
    )

    #expect(label == "banyan · main · \"implement the sidebar label\"")
}

@Test func displayLabelUsesReportedAgentSummaryWhenPreferred() {
    let label = SessionDisplayLabel.make(
        project: "banyan",
        branch: "main",
        title: "banyan",
        id: "session",
        command: "codex",
        reportedTitle: "Add inline sidebar rename",
        prefersReportedTitle: true
    )

    #expect(label == "banyan · main · \"Add inline sidebar rename\"")
}

@Test func displayLabelKeepsPinnedTitleOverReportedSummary() {
    let label = SessionDisplayLabel.make(
        project: "banyan",
        branch: "main",
        title: "Pinned name",
        id: "session",
        command: "claude",
        reportedTitle: "Autogenerated task summary",
        prefersReportedTitle: false
    )

    #expect(label == "banyan · main · \"Pinned name\"")
}

@Test func displayLabelIgnoresGenericReportedAgentTitle() {
    let label = SessionDisplayLabel.make(
        project: "banyan",
        branch: "main",
        title: "banyan",
        id: "session",
        command: "codex",
        reportedTitle: "codex",
        prefersReportedTitle: true
    )

    #expect(label == "banyan · main · \"banyan\"")
}
