import Testing
import Foundation
@testable import BanyanCore

@Test func displayLabelUsesProjectBranchAndExplicitTitle() {
    let label = SessionDisplayLabel.make(
        project: "banyan",
        branch: "main",
        title: "what's the label",
        id: "session",
        command: ""
    )

    #expect(label == "banyan · main · \"what's the label\"")
}

@Test func displayLabelFallsBackFromGenericTitleToShell() {
    let label = SessionDisplayLabel.make(
        project: "banyan",
        branch: "main",
        title: "Shell",
        id: "Shell-2",
        command: ""
    )

    #expect(label == "banyan · main · \"shell\"")
}

@Test func titleGeneratorDistinguishesGenericDefaultsFromProviderNames() {
    #expect(SessionTitleGenerator.isGenericDefaultTitle("shell-2"))
    #expect(SessionTitleGenerator.isGenericDefaultTitle("session"))
    #expect(!SessionTitleGenerator.isGenericDefaultTitle("codex"))
}

@Test func displayLabelIgnoresHostTitleAndUsesAgentPrompt() {
    let label = SessionDisplayLabel.make(
        project: "banyan",
        branch: "main",
        title: "user@Example-MacBook-Pro.local",
        id: "session",
        command: "codex implement the sidebar label"
    )

    #expect(label == "banyan · main · \"implement the sidebar label\"")
}

@Test func displayLabelUsesReportedAgentSummaryWhenPreferred() {
    let label = SessionDisplayLabel.make(
        project: "banyan",
        branch: "main",
        title: "banyan",
        id: "session",
        command: "codex",
        reportedTitle: "Add inline sidebar rename",
        prefersReportedTitle: true
    )

    #expect(label == "banyan · main · \"Add inline sidebar rename\"")
}

@Test func displayLabelKeepsPinnedTitleOverReportedSummary() {
    let label = SessionDisplayLabel.make(
        project: "banyan",
        branch: "main",
        title: "Pinned name",
        id: "session",
        command: "claude",
        reportedTitle: "Autogenerated task summary",
        prefersReportedTitle: false
    )

    #expect(label == "banyan · main · \"Pinned name\"")
}

@Test func displayLabelIgnoresGenericReportedAgentTitle() {
    let label = SessionDisplayLabel.make(
        project: "banyan",
        branch: "main",
        title: "banyan",
        id: "session",
        command: "codex",
        reportedTitle: "codex",
        prefersReportedTitle: true
    )

    #expect(label == "banyan · main · \"banyan\"")
}

@Test func projectContextUsesWorkingDirectoryOutsideGit() throws {
    let directory = try temporaryDirectory()
    defer { try? FileManager.default.removeItem(at: directory) }

    let context = SessionDisplayLabel.context(
        cwd: directory.path,
        homeDirectory: "/home/test",
        environment: [:]
    )

    #expect(context.project == directory.lastPathComponent)
    #expect(context.branch == nil)
    #expect(context.groupID == "path:\(directory.standardizedFileURL.path)")
    #expect(context.groupTitle == directory.lastPathComponent)
    #expect(context.isGitWorktree == false)
    #expect(context.isDefaultBranch == false)
    // A directory that simply isn't a git repo is a trustworthy negative, not a
    // failed lookup — it must not be flagged degraded (which would trigger retries).
    #expect(context.gitLookupDegraded == false)
}

@Test func projectContextCanonicalizesSymlinkedWorkingDirectoryOutsideGit() throws {
    let root = try temporaryDirectory()
    defer { try? FileManager.default.removeItem(at: root) }
    let directory = root.appendingPathComponent("project")
    let alias = root.appendingPathComponent("project-alias")
    try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
    try FileManager.default.createSymbolicLink(at: alias, withDestinationURL: directory)

    let directContext = SessionDisplayLabel.context(
        cwd: directory.path,
        homeDirectory: "/home/test",
        environment: [:]
    )
    let aliasContext = SessionDisplayLabel.context(
        cwd: alias.path,
        homeDirectory: "/home/test",
        environment: [:]
    )

    #expect(aliasContext.groupID == directContext.groupID)
    #expect(aliasContext.groupTitle == directContext.groupTitle)
    #expect(aliasContext.project == directContext.project)
}

@Test func projectContextGroupsGitRepositoriesByRemoteAddress() throws {
    let root = try temporaryDirectory()
    defer { try? FileManager.default.removeItem(at: root) }
    let first = root.appendingPathComponent("first")
    let second = root.appendingPathComponent("second")
    try FileManager.default.createDirectory(at: first, withIntermediateDirectories: true)
    try FileManager.default.createDirectory(at: second, withIntermediateDirectories: true)
    try runGit(["init"], cwd: first)
    try runGit(["init"], cwd: second)
    try runGit(["remote", "add", "origin", "git@github.com:yudu/banyan.git"], cwd: first)
    try runGit(["remote", "add", "origin", "https://github.com/yudu/banyan.git"], cwd: second)

    let firstContext = SessionDisplayLabel.context(
        cwd: first.path,
        homeDirectory: "/home/test",
        environment: [:]
    )
    let secondContext = SessionDisplayLabel.context(
        cwd: second.path,
        homeDirectory: "/home/test",
        environment: [:]
    )

    #expect(firstContext.groupID == "git:github.com/yudu/banyan")
    #expect(secondContext.groupID == firstContext.groupID)
    #expect(firstContext.groupTitle == "yudu/banyan")
}

@Test func projectContextGroupsGitWorktreesByMainDirectoryWithoutRemote() throws {
    let root = try temporaryDirectory()
    defer { try? FileManager.default.removeItem(at: root) }
    let main = root.appendingPathComponent("repo")
    let worktree = root.appendingPathComponent("repo-worktree")
    try FileManager.default.createDirectory(at: main, withIntermediateDirectories: true)
    try runGit(["init"], cwd: main)
    try runGit(["config", "user.email", "test@example.com"], cwd: main)
    try runGit(["config", "user.name", "Banyan Tests"], cwd: main)
    try "test".write(to: main.appendingPathComponent("README.md"), atomically: true, encoding: .utf8)
    try runGit(["add", "README.md"], cwd: main)
    try runGit(["commit", "-m", "Initial commit"], cwd: main)
    try runGit(["worktree", "add", "-b", "feature", worktree.path], cwd: main)

    let mainContext = SessionDisplayLabel.context(
        cwd: main.path,
        homeDirectory: "/home/test",
        environment: [:]
    )
    let worktreeContext = SessionDisplayLabel.context(
        cwd: worktree.path,
        homeDirectory: "/home/test",
        environment: [:]
    )

    #expect(mainContext.groupID == "path:\(main.standardizedFileURL.path)")
    #expect(worktreeContext.groupID == mainContext.groupID)
    #expect(worktreeContext.groupTitle == main.lastPathComponent)
    #expect(mainContext.isGitWorktree == false)
    #expect(worktreeContext.isGitWorktree == true)
    #expect(worktreeContext.branch == "feature")
    #expect(worktreeContext.isDefaultBranch == false)
    // Healthy git lookups must never be flagged degraded — a false positive here
    // would make idle worktree sessions retry the lookup on every tick.
    #expect(mainContext.gitLookupDegraded == false)
    #expect(worktreeContext.gitLookupDegraded == false)
}

@Test func projectContextGroupsGitWorktreesWithTheirRemoteRepository() throws {
    let root = try temporaryDirectory()
    defer { try? FileManager.default.removeItem(at: root) }
    let main = root.appendingPathComponent("repo")
    let worktree = main.appendingPathComponent(".worktrees").appendingPathComponent("feature-x")
    try FileManager.default.createDirectory(at: main, withIntermediateDirectories: true)
    try runGit(["init"], cwd: main)
    try runGit(["config", "user.email", "test@example.com"], cwd: main)
    try runGit(["config", "user.name", "Banyan Tests"], cwd: main)
    try runGit(["remote", "add", "origin", "git@github.com:yudu/banyan.git"], cwd: main)
    try "test".write(to: main.appendingPathComponent("README.md"), atomically: true, encoding: .utf8)
    try runGit(["add", "README.md"], cwd: main)
    try runGit(["commit", "-m", "Initial commit"], cwd: main)
    try runGit(["worktree", "add", "-b", "feature-x", worktree.path], cwd: main)

    let mainContext = SessionDisplayLabel.context(
        cwd: main.path,
        homeDirectory: "/home/test",
        environment: [:]
    )
    let worktreeContext = SessionDisplayLabel.context(
        cwd: worktree.path,
        homeDirectory: "/home/test",
        environment: [:]
    )

    // The user-visible regression: a worktree session must land in the same
    // sidebar group as its repository, keyed by the remote address — never in
    // a path-based group of its own.
    #expect(mainContext.groupID == "git:github.com/yudu/banyan")
    #expect(worktreeContext.groupID == mainContext.groupID)
    #expect(worktreeContext.groupTitle == "yudu/banyan")
    #expect(worktreeContext.isGitWorktree == true)
    #expect(worktreeContext.branch == "feature-x")
    #expect(worktreeContext.gitLookupDegraded == false)
}

@Test func workspaceRootResolvesWorktreeToMainCheckout() throws {
    let root = try temporaryDirectory()
    defer { try? FileManager.default.removeItem(at: root) }
    let main = root.appendingPathComponent("repo")
    let worktree = main.appendingPathComponent(".worktrees").appendingPathComponent("feature-x")
    try makeRepository(at: main)
    try runGit(["worktree", "add", "-b", "feature-x", worktree.path], cwd: main)

    let resolved = SessionDisplayLabel.workspaceRoot(cwd: worktree.path, environment: [:])

    // The user-visible behaviour: the project header's "+" opens the repository,
    // not the worktree the representative session happens to live in.
    #expect(resolved == main.standardizedFileURL.path)
}

@Test func workspaceRootResolvesSubdirectoryToRepositoryRoot() throws {
    let root = try temporaryDirectory()
    defer { try? FileManager.default.removeItem(at: root) }
    let main = root.appendingPathComponent("repo")
    let nested = main.appendingPathComponent("some").appendingPathComponent("subdir")
    try makeRepository(at: main)
    try FileManager.default.createDirectory(at: nested, withIntermediateDirectories: true)

    let resolved = SessionDisplayLabel.workspaceRoot(cwd: nested.path, environment: [:])

    #expect(resolved == main.standardizedFileURL.path)
}

@Test func workspaceRootKeepsMainCheckoutUnchanged() throws {
    let root = try temporaryDirectory()
    defer { try? FileManager.default.removeItem(at: root) }
    let main = root.appendingPathComponent("repo")
    try makeRepository(at: main)

    let resolved = SessionDisplayLabel.workspaceRoot(cwd: main.path, environment: [:])

    #expect(resolved == main.standardizedFileURL.path)
}

@Test func workspaceRootFallsBackToWorkingDirectoryOutsideGit() throws {
    let directory = try temporaryDirectory()
    defer { try? FileManager.default.removeItem(at: directory) }

    let resolved = SessionDisplayLabel.workspaceRoot(cwd: directory.path, environment: [:])

    #expect(resolved == directory.standardizedFileURL.path)
}

@Test func workspaceRootKeepsSubmoduleCheckoutOutOfGitInternals() throws {
    let root = try temporaryDirectory()
    defer { try? FileManager.default.removeItem(at: root) }
    let upstream = root.appendingPathComponent("upstream")
    let main = root.appendingPathComponent("repo")
    try makeRepository(at: upstream)
    try makeRepository(at: main)
    try runGit(
        ["-c", "protocol.file.allow=always", "submodule", "add", upstream.path, "sub"],
        cwd: main
    )
    let submodule = main.appendingPathComponent("sub")

    let resolved = SessionDisplayLabel.workspaceRoot(cwd: submodule.path, environment: [:])

    // A submodule's `--git-common-dir` is `<repo>/.git/modules/sub`; spawning
    // there would drop the session inside git internals. Its own checkout is
    // the workspace root.
    #expect(resolved == submodule.standardizedFileURL.path)
}

private func makeRepository(at directory: URL) throws {
    try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
    try runGit(["init"], cwd: directory)
    try runGit(["config", "user.email", "test@example.com"], cwd: directory)
    try runGit(["config", "user.name", "Banyan Tests"], cwd: directory)
    try "test".write(to: directory.appendingPathComponent("README.md"), atomically: true, encoding: .utf8)
    try runGit(["add", "README.md"], cwd: directory)
    try runGit(["commit", "-m", "Initial commit"], cwd: directory)
}

private func temporaryDirectory() throws -> URL {
    let directory = FileManager.default.temporaryDirectory
        .appendingPathComponent("BanyanCoreTests-\(UUID().uuidString)")
    try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
    return directory
}

@discardableResult
private func runGit(_ arguments: [String], cwd: URL) throws -> String {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
    process.arguments = ["git"] + arguments
    process.currentDirectoryURL = cwd
    let stdout = Pipe()
    let stderr = Pipe()
    process.standardOutput = stdout
    process.standardError = stderr
    try process.run()
    process.waitUntilExit()

    let output = String(data: stdout.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8) ?? ""
    if process.terminationStatus != 0 {
        let message = String(data: stderr.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8) ?? ""
        throw GitTestError(arguments: arguments, message: message)
    }
    return output.trimmingCharacters(in: .whitespacesAndNewlines)
}

private struct GitTestError: Error, CustomStringConvertible {
    let arguments: [String]
    let message: String

    var description: String {
        "git \(arguments.joined(separator: " ")) failed: \(message)"
    }
}
